spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://h2:1521/subway;MODE=MySQL
    username: sa
    password:
