# 프로덕션 환경
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/subway
    username: sa
    password:
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

# 테스트 환경
---
spring:
  datasource:
    url: jdbc:h2:mem:test-subway
  config:
    activate:
      on-profile: test
