spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/subway
    username: SA
    password:
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

springdoc:
  packages-to-scan: subway
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: subway.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /subway-api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
